import React, { useEffect, useState } from "react";
import Faq from "react-faq-component";

const data = {
    title: "FREQUENTLY ASKED QUESTION",
    rowContentTextSize: "10px",
    rows: [
        {
            title: "WHAT IS SOLAR ENERGY?",
            content: `A Solar energy is a renewable and sustainable form of energy derived from the sun's radiation. It is harnessed through photovoltaic (PV) cells or solar panels, which convert sunlight into electricity. Solar energy is environmentally friendly, reduces dependence on fossil fuels, and can be utilized for residential, commercial, and industrial purposes.`,
        },


        {
            title: "HOW DO SOLAR PANELS WORK?",
            content:
                "Solar panels work by using photovoltaic cells to convert sunlight into electricity. These cells are typically made of silicon and consist of two layers with opposite charges. When sunlight hits the cells, it excites the electrons, creating an electric current that can be harnessed as usable electricity. This direct current (DC) electricity is then converted into alternating current (AC) using an inverter, making it suitable for powering household appliances and devices.",
        },

        {
            title: "WHAT ARE THE BENEFITS OF USING SOLAR ENERGY?",
            content: ` Using solar energy offers several benefits, including reduced electricity bills, lower carbon footprint, and energy independence. Solar power helps decrease reliance on fossil fuels, leading to a cleaner environment and mitigating climate change. Additionally, solar panels have a long lifespan and require minimal maintenance, making them a cost-effective and sustainable energy solution in the long run.`,
        },

        {
            title: "WHAT IS THE ROLE OF BATTERIES IN A SOLAR ENERGY SYSTEM?",
            content: `Batteries play a crucial role in a solar energy system by enabling energy storage. During sunny periods, excess electricity generated by solar panels can be stored in batteries instead of being fed back into the grid. These batteries then provide power during cloudy days or at night when solar generation is limited or unavailable. Battery storage enhances the self-consumption of solar energy and increases energy resilience, ensuring a continuous power supply even in the absence of sunlight.`,
        },

        {
            title: "WHAT IS THE FUNCTION OF AN INVERTER IN A SOLAR ENERGY SYSTEM?",
            content: `An inverter is an essential component of a solar energy system as it converts the direct current (DC) electricity produced by solar panels into the alternating current (AC) used in homes and businesses. AC electricity is the standard form of power used by most electrical devices and appliances. Inverters also allow the solar system to synchronize with the grid, enabling users to sell excess electricity back to the utility company through a process called net metering.`,
        },

        {
            title: "WHAT FACTORS SHOULD BE CONSIDERED WHEN INSTALLING A SOLAR ENERGY SYSTEM?",
            content: `When installing a solar energy system, several factors must be considered, including the location and orientation of the solar panels for optimal sunlight exposure, the size of the system based on energy needs, the quality and efficiency of solar panels and inverters, and the available budget for the installation. Local regulations, incentives, and rebates related to solar energy should also be researched to maximize the financial benefits of the solar installation. Consulting with a reputable solar provider and conducting a thorough energy audit can help determine the most suitable solar system for individual needs and circumstances.`,
        },

    
    ],
};

const styles = {
    // bgColor: 'white',
    titleTextColor: "black",
    rowTitleColor: "black",
    position:"relative",
    // rowContentColor: 'grey',
    // arrowColor: "red",
};

const config = {
     animate: true,
    // arrowIcon: "V",
    // tabFocus: true

    expandIcon: "+",
    collapseIcon: "-",
    transitionDuration: "1s",
};

export default function CartPageFaq(){

    return (
        <div className="fof text-4xl my-24 wrapper">
            <Faq
                data={data}
                styles={styles}
                config={config}
                className="relative"
            />
        </div>
    );
}